package com.qigan.qiganshop.domain;

import java.util.Date;

public class TbDeliverInfoModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_deliver_info.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_deliver_info.order_id_
	 * @mbg.generated
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_deliver_info.user_id_
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_deliver_info.user_name_
	 * @mbg.generated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_deliver_info.dict_type_
	 * @mbg.generated
	 */
	private String dictType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_deliver_info.dict_name_
	 * @mbg.generated
	 */
	private String dictName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_deliver_info.content
	 * @mbg.generated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_deliver_info.create_date_
	 * @mbg.generated
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_deliver_info.id
	 * @return  the value of tb_deliver_info.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_deliver_info.id
	 * @param id  the value for tb_deliver_info.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_deliver_info.order_id_
	 * @return  the value of tb_deliver_info.order_id_
	 * @mbg.generated
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_deliver_info.order_id_
	 * @param orderId  the value for tb_deliver_info.order_id_
	 * @mbg.generated
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_deliver_info.user_id_
	 * @return  the value of tb_deliver_info.user_id_
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_deliver_info.user_id_
	 * @param userId  the value for tb_deliver_info.user_id_
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_deliver_info.user_name_
	 * @return  the value of tb_deliver_info.user_name_
	 * @mbg.generated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_deliver_info.user_name_
	 * @param userName  the value for tb_deliver_info.user_name_
	 * @mbg.generated
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_deliver_info.dict_type_
	 * @return  the value of tb_deliver_info.dict_type_
	 * @mbg.generated
	 */
	public String getDictType() {
		return dictType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_deliver_info.dict_type_
	 * @param dictType  the value for tb_deliver_info.dict_type_
	 * @mbg.generated
	 */
	public void setDictType(String dictType) {
		this.dictType = dictType == null ? null : dictType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_deliver_info.dict_name_
	 * @return  the value of tb_deliver_info.dict_name_
	 * @mbg.generated
	 */
	public String getDictName() {
		return dictName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_deliver_info.dict_name_
	 * @param dictName  the value for tb_deliver_info.dict_name_
	 * @mbg.generated
	 */
	public void setDictName(String dictName) {
		this.dictName = dictName == null ? null : dictName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_deliver_info.content
	 * @return  the value of tb_deliver_info.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_deliver_info.content
	 * @param content  the value for tb_deliver_info.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_deliver_info.create_date_
	 * @return  the value of tb_deliver_info.create_date_
	 * @mbg.generated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_deliver_info.create_date_
	 * @param createDate  the value for tb_deliver_info.create_date_
	 * @mbg.generated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}