package com.qigan.qiganshop.domain;

import java.util.ArrayList;
import java.util.List;

public class TbLocalGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public TbLocalGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Long value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Long value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Long value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Long value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Long> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Long> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Long value1, Long value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidIsNull() {
            addCriterion("tb_goodsId is null");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidIsNotNull() {
            addCriterion("tb_goodsId is not null");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidEqualTo(String value) {
            addCriterion("tb_goodsId =", value, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidNotEqualTo(String value) {
            addCriterion("tb_goodsId <>", value, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidGreaterThan(String value) {
            addCriterion("tb_goodsId >", value, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidGreaterThanOrEqualTo(String value) {
            addCriterion("tb_goodsId >=", value, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidLessThan(String value) {
            addCriterion("tb_goodsId <", value, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidLessThanOrEqualTo(String value) {
            addCriterion("tb_goodsId <=", value, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidLike(String value) {
            addCriterion("tb_goodsId like", value, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidNotLike(String value) {
            addCriterion("tb_goodsId not like", value, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidIn(List<String> values) {
            addCriterion("tb_goodsId in", values, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidNotIn(List<String> values) {
            addCriterion("tb_goodsId not in", values, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidBetween(String value1, String value2) {
            addCriterion("tb_goodsId between", value1, value2, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andTbGoodsidNotBetween(String value1, String value2) {
            addCriterion("tb_goodsId not between", value1, value2, "tbGoodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIsNull() {
            addCriterion("goods_sort is null");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIsNotNull() {
            addCriterion("goods_sort is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsSortEqualTo(Integer value) {
            addCriterion("goods_sort =", value, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsSortNotEqualTo(Integer value) {
            addCriterion("goods_sort <>", value, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsSortGreaterThan(Integer value) {
            addCriterion("goods_sort >", value, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_sort >=", value, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsSortLessThan(Integer value) {
            addCriterion("goods_sort <", value, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsSortLessThanOrEqualTo(Integer value) {
            addCriterion("goods_sort <=", value, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsSortIn(List<Integer> values) {
            addCriterion("goods_sort in", values, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsSortNotIn(List<Integer> values) {
            addCriterion("goods_sort not in", values, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsSortBetween(Integer value1, Integer value2) {
            addCriterion("goods_sort between", value1, value2, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsSortNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_sort not between", value1, value2, "goodsSort");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableIsNull() {
            addCriterion("goods_enable is null");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableIsNotNull() {
            addCriterion("goods_enable is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableEqualTo(String value) {
            addCriterion("goods_enable =", value, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableNotEqualTo(String value) {
            addCriterion("goods_enable <>", value, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableGreaterThan(String value) {
            addCriterion("goods_enable >", value, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableGreaterThanOrEqualTo(String value) {
            addCriterion("goods_enable >=", value, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableLessThan(String value) {
            addCriterion("goods_enable <", value, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableLessThanOrEqualTo(String value) {
            addCriterion("goods_enable <=", value, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableLike(String value) {
            addCriterion("goods_enable like", value, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableNotLike(String value) {
            addCriterion("goods_enable not like", value, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableIn(List<String> values) {
            addCriterion("goods_enable in", values, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableNotIn(List<String> values) {
            addCriterion("goods_enable not in", values, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableBetween(String value1, String value2) {
            addCriterion("goods_enable between", value1, value2, "goodsEnable");
            return (Criteria) this;
        }

        public Criteria andGoodsEnableNotBetween(String value1, String value2) {
            addCriterion("goods_enable not between", value1, value2, "goodsEnable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_local_goods
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}