package com.qigan.qiganshop.domain;

import java.math.BigDecimal;
import java.util.Date;

import com.qigan.qiganshop.pojo.CommonPage;

public class TbOrderComment extends CommonPage{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_comment.comment_id
     *
     * @mbg.generated
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_comment.orderId
     *
     * @mbg.generated
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_comment.delivery_level
     *
     * @mbg.generated
     */
    private BigDecimal deliveryLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_comment.delivery_comment
     *
     * @mbg.generated
     */
    private String deliveryComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_comment.goods_level
     *
     * @mbg.generated
     */
    private BigDecimal goodsLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_comment.goods_comment
     *
     * @mbg.generated
     */
    private String goodsComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_comment.comment_context
     *
     * @mbg.generated
     */
    private String commentContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_comment.user_phone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_comment.create_date
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_comment.comment_id
     *
     * @return the value of tb_order_comment.comment_id
     *
     * @mbg.generated
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_comment.comment_id
     *
     * @param commentId the value for tb_order_comment.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_comment.orderId
     *
     * @return the value of tb_order_comment.orderId
     *
     * @mbg.generated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_comment.orderId
     *
     * @param orderid the value for tb_order_comment.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_comment.delivery_level
     *
     * @return the value of tb_order_comment.delivery_level
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryLevel() {
        return deliveryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_comment.delivery_level
     *
     * @param deliveryLevel the value for tb_order_comment.delivery_level
     *
     * @mbg.generated
     */
    public void setDeliveryLevel(BigDecimal deliveryLevel) {
        this.deliveryLevel = deliveryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_comment.delivery_comment
     *
     * @return the value of tb_order_comment.delivery_comment
     *
     * @mbg.generated
     */
    public String getDeliveryComment() {
        return deliveryComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_comment.delivery_comment
     *
     * @param deliveryComment the value for tb_order_comment.delivery_comment
     *
     * @mbg.generated
     */
    public void setDeliveryComment(String deliveryComment) {
        this.deliveryComment = deliveryComment == null ? null : deliveryComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_comment.goods_level
     *
     * @return the value of tb_order_comment.goods_level
     *
     * @mbg.generated
     */
    public BigDecimal getGoodsLevel() {
        return goodsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_comment.goods_level
     *
     * @param goodsLevel the value for tb_order_comment.goods_level
     *
     * @mbg.generated
     */
    public void setGoodsLevel(BigDecimal goodsLevel) {
        this.goodsLevel = goodsLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_comment.goods_comment
     *
     * @return the value of tb_order_comment.goods_comment
     *
     * @mbg.generated
     */
    public String getGoodsComment() {
        return goodsComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_comment.goods_comment
     *
     * @param goodsComment the value for tb_order_comment.goods_comment
     *
     * @mbg.generated
     */
    public void setGoodsComment(String goodsComment) {
        this.goodsComment = goodsComment == null ? null : goodsComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_comment.comment_context
     *
     * @return the value of tb_order_comment.comment_context
     *
     * @mbg.generated
     */
    public String getCommentContext() {
        return commentContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_comment.comment_context
     *
     * @param commentContext the value for tb_order_comment.comment_context
     *
     * @mbg.generated
     */
    public void setCommentContext(String commentContext) {
        this.commentContext = commentContext == null ? null : commentContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_comment.user_phone
     *
     * @return the value of tb_order_comment.user_phone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_comment.user_phone
     *
     * @param userPhone the value for tb_order_comment.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_comment.create_date
     *
     * @return the value of tb_order_comment.create_date
     *
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_comment.create_date
     *
     * @param createDate the value for tb_order_comment.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
}