package com.qigan.qiganshop.domain;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.qigan.qiganshop.pojo.CommonPage;

public class TbPushRecord extends CommonPage{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_push_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_push_record.push_title
     *
     * @mbg.generated
     */
    private String pushTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_push_record.push_no
     *
     * @mbg.generated
     */
    private String pushNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_push_record.push_num
     *
     * @mbg.generated
     */
    private Integer pushNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_push_record.push_type
     *
     * @mbg.generated
     */
    private String pushType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_push_record.create_date
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_push_record.push_message
     *
     * @mbg.generated
     */
    private String pushMessage;
    
    private String startDate;
    
    private String endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_push_record.id
     *
     * @return the value of tb_push_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_push_record.id
     *
     * @param id the value for tb_push_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_push_record.push_title
     *
     * @return the value of tb_push_record.push_title
     *
     * @mbg.generated
     */
    public String getPushTitle() {
        return pushTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_push_record.push_title
     *
     * @param pushTitle the value for tb_push_record.push_title
     *
     * @mbg.generated
     */
    public void setPushTitle(String pushTitle) {
        this.pushTitle = pushTitle == null ? null : pushTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_push_record.push_no
     *
     * @return the value of tb_push_record.push_no
     *
     * @mbg.generated
     */
    public String getPushNo() {
        return pushNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_push_record.push_no
     *
     * @param pushNo the value for tb_push_record.push_no
     *
     * @mbg.generated
     */
    public void setPushNo(String pushNo) {
        this.pushNo = pushNo == null ? null : pushNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_push_record.push_num
     *
     * @return the value of tb_push_record.push_num
     *
     * @mbg.generated
     */
    public Integer getPushNum() {
        return pushNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_push_record.push_num
     *
     * @param pushNum the value for tb_push_record.push_num
     *
     * @mbg.generated
     */
    public void setPushNum(Integer pushNum) {
        this.pushNum = pushNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_push_record.push_type
     *
     * @return the value of tb_push_record.push_type
     *
     * @mbg.generated
     */
    public String getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_push_record.push_type
     *
     * @param pushType the value for tb_push_record.push_type
     *
     * @mbg.generated
     */
    public void setPushType(String pushType) {
        this.pushType = pushType == null ? null : pushType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_push_record.create_date
     *
     * @return the value of tb_push_record.create_date
     *
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_push_record.create_date
     *
     * @param createDate the value for tb_push_record.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_push_record.push_message
     *
     * @return the value of tb_push_record.push_message
     *
     * @mbg.generated
     */
    public String getPushMessage() {
        return pushMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_push_record.push_message
     *
     * @param pushMessage the value for tb_push_record.push_message
     *
     * @mbg.generated
     */
    public void setPushMessage(String pushMessage) {
        this.pushMessage = pushMessage == null ? null : pushMessage.trim();
    }

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}
}