package com.qigan.qiganshop.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbPushRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public TbPushRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPushTitleIsNull() {
            addCriterion("push_title is null");
            return (Criteria) this;
        }

        public Criteria andPushTitleIsNotNull() {
            addCriterion("push_title is not null");
            return (Criteria) this;
        }

        public Criteria andPushTitleEqualTo(String value) {
            addCriterion("push_title =", value, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleNotEqualTo(String value) {
            addCriterion("push_title <>", value, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleGreaterThan(String value) {
            addCriterion("push_title >", value, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleGreaterThanOrEqualTo(String value) {
            addCriterion("push_title >=", value, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleLessThan(String value) {
            addCriterion("push_title <", value, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleLessThanOrEqualTo(String value) {
            addCriterion("push_title <=", value, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleLike(String value) {
            addCriterion("push_title like", value, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleNotLike(String value) {
            addCriterion("push_title not like", value, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleIn(List<String> values) {
            addCriterion("push_title in", values, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleNotIn(List<String> values) {
            addCriterion("push_title not in", values, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleBetween(String value1, String value2) {
            addCriterion("push_title between", value1, value2, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushTitleNotBetween(String value1, String value2) {
            addCriterion("push_title not between", value1, value2, "pushTitle");
            return (Criteria) this;
        }

        public Criteria andPushNoIsNull() {
            addCriterion("push_no is null");
            return (Criteria) this;
        }

        public Criteria andPushNoIsNotNull() {
            addCriterion("push_no is not null");
            return (Criteria) this;
        }

        public Criteria andPushNoEqualTo(String value) {
            addCriterion("push_no =", value, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoNotEqualTo(String value) {
            addCriterion("push_no <>", value, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoGreaterThan(String value) {
            addCriterion("push_no >", value, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoGreaterThanOrEqualTo(String value) {
            addCriterion("push_no >=", value, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoLessThan(String value) {
            addCriterion("push_no <", value, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoLessThanOrEqualTo(String value) {
            addCriterion("push_no <=", value, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoLike(String value) {
            addCriterion("push_no like", value, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoNotLike(String value) {
            addCriterion("push_no not like", value, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoIn(List<String> values) {
            addCriterion("push_no in", values, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoNotIn(List<String> values) {
            addCriterion("push_no not in", values, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoBetween(String value1, String value2) {
            addCriterion("push_no between", value1, value2, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNoNotBetween(String value1, String value2) {
            addCriterion("push_no not between", value1, value2, "pushNo");
            return (Criteria) this;
        }

        public Criteria andPushNumIsNull() {
            addCriterion("push_num is null");
            return (Criteria) this;
        }

        public Criteria andPushNumIsNotNull() {
            addCriterion("push_num is not null");
            return (Criteria) this;
        }

        public Criteria andPushNumEqualTo(Integer value) {
            addCriterion("push_num =", value, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushNumNotEqualTo(Integer value) {
            addCriterion("push_num <>", value, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushNumGreaterThan(Integer value) {
            addCriterion("push_num >", value, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("push_num >=", value, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushNumLessThan(Integer value) {
            addCriterion("push_num <", value, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushNumLessThanOrEqualTo(Integer value) {
            addCriterion("push_num <=", value, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushNumIn(List<Integer> values) {
            addCriterion("push_num in", values, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushNumNotIn(List<Integer> values) {
            addCriterion("push_num not in", values, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushNumBetween(Integer value1, Integer value2) {
            addCriterion("push_num between", value1, value2, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushNumNotBetween(Integer value1, Integer value2) {
            addCriterion("push_num not between", value1, value2, "pushNum");
            return (Criteria) this;
        }

        public Criteria andPushTypeIsNull() {
            addCriterion("push_type is null");
            return (Criteria) this;
        }

        public Criteria andPushTypeIsNotNull() {
            addCriterion("push_type is not null");
            return (Criteria) this;
        }

        public Criteria andPushTypeEqualTo(String value) {
            addCriterion("push_type =", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotEqualTo(String value) {
            addCriterion("push_type <>", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeGreaterThan(String value) {
            addCriterion("push_type >", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeGreaterThanOrEqualTo(String value) {
            addCriterion("push_type >=", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeLessThan(String value) {
            addCriterion("push_type <", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeLessThanOrEqualTo(String value) {
            addCriterion("push_type <=", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeLike(String value) {
            addCriterion("push_type like", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotLike(String value) {
            addCriterion("push_type not like", value, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeIn(List<String> values) {
            addCriterion("push_type in", values, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotIn(List<String> values) {
            addCriterion("push_type not in", values, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeBetween(String value1, String value2) {
            addCriterion("push_type between", value1, value2, "pushType");
            return (Criteria) this;
        }

        public Criteria andPushTypeNotBetween(String value1, String value2) {
            addCriterion("push_type not between", value1, value2, "pushType");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_push_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}