package com.qigan.qiganshop.domain;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class TbLocalCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_category.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_category.type_code
     *
     * @mbg.generated
     */
    private String typeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_category.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_category.type_sort
     *
     * @mbg.generated
     */
    private Integer typeSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_category.type_enable
     *
     * @mbg.generated
     */
    private String typeEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_category.create_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_category.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_category.update_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_category.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_category.id
     *
     * @return the value of tb_local_category.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_category.id
     *
     * @param id the value for tb_local_category.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_category.type_code
     *
     * @return the value of tb_local_category.type_code
     *
     * @mbg.generated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_category.type_code
     *
     * @param typeCode the value for tb_local_category.type_code
     *
     * @mbg.generated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_category.type_name
     *
     * @return the value of tb_local_category.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_category.type_name
     *
     * @param typeName the value for tb_local_category.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_category.type_sort
     *
     * @return the value of tb_local_category.type_sort
     *
     * @mbg.generated
     */
    public Integer getTypeSort() {
        return typeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_category.type_sort
     *
     * @param typeSort the value for tb_local_category.type_sort
     *
     * @mbg.generated
     */
    public void setTypeSort(Integer typeSort) {
        this.typeSort = typeSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_category.type_enable
     *
     * @return the value of tb_local_category.type_enable
     *
     * @mbg.generated
     */
    public String getTypeEnable() {
        return typeEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_category.type_enable
     *
     * @param typeEnable the value for tb_local_category.type_enable
     *
     * @mbg.generated
     */
    public void setTypeEnable(String typeEnable) {
        this.typeEnable = typeEnable == null ? null : typeEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_category.create_date
     *
     * @return the value of tb_local_category.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_category.create_date
     *
     * @param createDate the value for tb_local_category.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_category.creater
     *
     * @return the value of tb_local_category.creater
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_category.creater
     *
     * @param creater the value for tb_local_category.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_category.update_date
     *
     * @return the value of tb_local_category.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_category.update_date
     *
     * @param updateDate the value for tb_local_category.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_category.updater
     *
     * @return the value of tb_local_category.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_category.updater
     *
     * @param updater the value for tb_local_category.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}