package com.qigan.qiganshop.domain;

import java.util.Date;

public class TbDictModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.dict_type_
     *
     * @mbg.generated
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.dict_code_
     *
     * @mbg.generated
     */
    private String dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.dict_name_
     *
     * @mbg.generated
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.create_date_
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.update_date_
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.id
     *
     * @return the value of tb_dict.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.id
     *
     * @param id the value for tb_dict.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.dict_type_
     *
     * @return the value of tb_dict.dict_type_
     *
     * @mbg.generated
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.dict_type_
     *
     * @param dictType the value for tb_dict.dict_type_
     *
     * @mbg.generated
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.dict_code_
     *
     * @return the value of tb_dict.dict_code_
     *
     * @mbg.generated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.dict_code_
     *
     * @param dictCode the value for tb_dict.dict_code_
     *
     * @mbg.generated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.dict_name_
     *
     * @return the value of tb_dict.dict_name_
     *
     * @mbg.generated
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.dict_name_
     *
     * @param dictName the value for tb_dict.dict_name_
     *
     * @mbg.generated
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.create_date_
     *
     * @return the value of tb_dict.create_date_
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.create_date_
     *
     * @param createDate the value for tb_dict.create_date_
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.update_date_
     *
     * @return the value of tb_dict.update_date_
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.update_date_
     *
     * @param updateDate the value for tb_dict.update_date_
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.creater
     *
     * @return the value of tb_dict.creater
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.creater
     *
     * @param creater the value for tb_dict.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.updater
     *
     * @return the value of tb_dict.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.updater
     *
     * @param updater the value for tb_dict.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}