package com.qigan.qiganshop.mapper;

import com.qigan.qiganshop.domain.TbPushRecord;
import com.qigan.qiganshop.domain.TbPushRecordExample.Criteria;
import com.qigan.qiganshop.domain.TbPushRecordExample.Criterion;
import com.qigan.qiganshop.domain.TbPushRecordExample;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;
import org.apache.ibatis.jdbc.SQL;

public class TbPushRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String countByExample(TbPushRecordExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_push_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String deleteByExample(TbPushRecordExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_push_record");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String insertSelective(TbPushRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_push_record");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getPushTitle() != null) {
            sql.VALUES("push_title", "#{pushTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getPushNo() != null) {
            sql.VALUES("push_no", "#{pushNo,jdbcType=VARCHAR}");
        }
        
        if (record.getPushNum() != null) {
            sql.VALUES("push_num", "#{pushNum,jdbcType=INTEGER}");
        }
        
        if (record.getPushType() != null) {
            sql.VALUES("push_type", "#{pushType,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            sql.VALUES("create_date", "#{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPushMessage() != null) {
            sql.VALUES("push_message", "#{pushMessage,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String selectByExampleWithBLOBs(TbPushRecordExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("push_title");
        sql.SELECT("push_no");
        sql.SELECT("push_num");
        sql.SELECT("push_type");
        sql.SELECT("create_date");
        sql.SELECT("push_message");
        sql.FROM("tb_push_record");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String selectByExample(TbPushRecordExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("push_title");
        sql.SELECT("push_no");
        sql.SELECT("push_num");
        sql.SELECT("push_type");
        sql.SELECT("create_date");
        sql.FROM("tb_push_record");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TbPushRecord record = (TbPushRecord) parameter.get("record");
        TbPushRecordExample example = (TbPushRecordExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("tb_push_record");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getPushTitle() != null) {
            sql.SET("push_title = #{record.pushTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getPushNo() != null) {
            sql.SET("push_no = #{record.pushNo,jdbcType=VARCHAR}");
        }
        
        if (record.getPushNum() != null) {
            sql.SET("push_num = #{record.pushNum,jdbcType=INTEGER}");
        }
        
        if (record.getPushType() != null) {
            sql.SET("push_type = #{record.pushType,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            sql.SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPushMessage() != null) {
            sql.SET("push_message = #{record.pushMessage,jdbcType=LONGVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_push_record");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("push_title = #{record.pushTitle,jdbcType=VARCHAR}");
        sql.SET("push_no = #{record.pushNo,jdbcType=VARCHAR}");
        sql.SET("push_num = #{record.pushNum,jdbcType=INTEGER}");
        sql.SET("push_type = #{record.pushType,jdbcType=VARCHAR}");
        sql.SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
        sql.SET("push_message = #{record.pushMessage,jdbcType=LONGVARCHAR}");
        
        TbPushRecordExample example = (TbPushRecordExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_push_record");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("push_title = #{record.pushTitle,jdbcType=VARCHAR}");
        sql.SET("push_no = #{record.pushNo,jdbcType=VARCHAR}");
        sql.SET("push_num = #{record.pushNum,jdbcType=INTEGER}");
        sql.SET("push_type = #{record.pushType,jdbcType=VARCHAR}");
        sql.SET("create_date = #{record.createDate,jdbcType=TIMESTAMP}");
        
        TbPushRecordExample example = (TbPushRecordExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TbPushRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_push_record");
        
        if (record.getPushTitle() != null) {
            sql.SET("push_title = #{pushTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getPushNo() != null) {
            sql.SET("push_no = #{pushNo,jdbcType=VARCHAR}");
        }
        
        if (record.getPushNum() != null) {
            sql.SET("push_num = #{pushNum,jdbcType=INTEGER}");
        }
        
        if (record.getPushType() != null) {
            sql.SET("push_type = #{pushType,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            sql.SET("create_date = #{createDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getPushMessage() != null) {
            sql.SET("push_message = #{pushMessage,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
    
    public String selectByCodition(TbPushRecord model){
    	SQL sql = new SQL();
    	sql.SELECT("id");
    	sql.SELECT("push_title");
        sql.SELECT("push_no");
        sql.SELECT("push_num");
        sql.SELECT("push_type");
        sql.SELECT("date_format(create_date, '%Y-%m-%d %T') as create_date ");
        sql.SELECT("push_message");
        sql.FROM("tb_push_record");
        if(StringUtils.isNotBlank(model.getPushMessage())){
        	sql.WHERE("push_message like '%" + model.getPushMessage() + "%'");
        }
    	if(StringUtils.isNotBlank(model.getPushTitle())){
    		sql.WHERE("push_title like '%" + model.getPushTitle() + "%'");
    	}
    	if(StringUtils.isNotBlank(model.getPushType())){
    		sql.WHERE("push_type = '" + model.getPushType() + "'");
    	}
    	if(StringUtils.isNotBlank(model.getPushNo())){
    		sql.WHERE("push_no = '" + model.getPushNo() + "'");
    	}
    	if(StringUtils.isNotBlank(model.getStartDate()) && StringUtils.isNotBlank(model.getEndDate())){
    		sql.WHERE("date_format(create_date, '%Y-%m-%d') between '" + model.getStartDate() +"' and '" + model.getEndDate() + "'");
    	}
    	sql.ORDER_BY("create_date desc");
    	return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TbPushRecordExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}