package com.qigan.qiganshop.mapper;

import com.qigan.qiganshop.constant.DataState;
import com.qigan.qiganshop.domain.TbCouponDetails;
import com.qigan.qiganshop.domain.TbCouponDetailsExample;
import com.qigan.qiganshop.pojo.XltcGoodsModel;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TbCouponDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbCouponDetailsSqlProvider.class, method="countByExample")
    long countByExample(TbCouponDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TbCouponDetailsSqlProvider.class, method="deleteByExample")
    int deleteByExample(TbCouponDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_coupon_details",
        "where detailsId = #{detailsid,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long detailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_coupon_details (detailsId, couponId, ",
        "goodsCode, typeId, ",
        "type, status)",
        "values (#{detailsid,jdbcType=BIGINT}, #{couponid,jdbcType=VARCHAR}, ",
        "#{goodscode,jdbcType=VARCHAR}, #{typeid,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR})"
    })
    int insert(TbCouponDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @InsertProvider(type=TbCouponDetailsSqlProvider.class, method="insertSelective")
    int insertSelective(TbCouponDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbCouponDetailsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="detailsId", property="detailsid", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="couponId", property="couponid", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodsCode", property="goodscode", jdbcType=JdbcType.VARCHAR),
        @Result(column="typeId", property="typeid", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR)
    })
    List<TbCouponDetails> selectByExample(TbCouponDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "detailsId, couponId, goodsCode, typeId, type, status",
        "from tb_coupon_details",
        "where detailsId = #{detailsid,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="detailsId", property="detailsid", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="couponId", property="couponid", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodsCode", property="goodscode", jdbcType=JdbcType.VARCHAR),
        @Result(column="typeId", property="typeid", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR)
    })
    TbCouponDetails selectByPrimaryKey(Long detailsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbCouponDetailsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TbCouponDetails record, @Param("example") TbCouponDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbCouponDetailsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TbCouponDetails record, @Param("example") TbCouponDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbCouponDetailsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TbCouponDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_details
     *
     * @mbg.generated
     */
    @Update({
        "update tb_coupon_details",
        "set couponId = #{couponid,jdbcType=VARCHAR},",
          "goodsCode = #{goodscode,jdbcType=VARCHAR},",
          "typeId = #{typeid,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR}",
        "where detailsId = #{detailsid,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TbCouponDetails record);
    
    
    @Select({
    	"select x.goodsId, x.name as goodsName, x.code as goodsCode, x.simpleName as simpleName, x.salesPrice, ",
    	"x.VIPrice, x.costPrice, categoryName ",
    	"from tb_coupon_details t ",
    	"left join tb_goods x on x.code = t.goodsCode ",
    	"where t.status = '" + DataState.NOR + "' and t.couponId = #{couponId}"
    })
    List<XltcGoodsModel> selectCouponDetails(String couponId);
    
    @Select({
    	"select distinct goodsCode from tb_coupon_details",
    	"where status = '" + DataState.NOR + "'",
    	"and couponId = #{couponId}"
    })
    List<String> selectGoodsCodes(String couponId);
    
    @Select({
    	"select distinct typeId from tb_coupon_details",
    	"where status = '" + DataState.NOR + "'",
    	"and couponId = #{couponId}"
    })
    List<String> selectTypeCodes(String couponId);
}