package com.qigan.qiganshop.mapper;

import com.qigan.qiganshop.domain.TbDeliverInfoModel;
import com.qigan.qiganshop.domain.TbDeliverInfoModelExample.Criteria;
import com.qigan.qiganshop.domain.TbDeliverInfoModelExample.Criterion;
import com.qigan.qiganshop.domain.TbDeliverInfoModelExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbDeliverInfoModelSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_deliver_info
	 * @mbg.generated
	 */
	public String countByExample(TbDeliverInfoModelExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("tb_deliver_info");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_deliver_info
	 * @mbg.generated
	 */
	public String deleteByExample(TbDeliverInfoModelExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("tb_deliver_info");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_deliver_info
	 * @mbg.generated
	 */
	public String insertSelective(TbDeliverInfoModel record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("tb_deliver_info");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=BIGINT}");
		}
		if (record.getOrderId() != null) {
			sql.VALUES("order_id_", "#{orderId,jdbcType=VARCHAR}");
		}
		if (record.getUserId() != null) {
			sql.VALUES("user_id_", "#{userId,jdbcType=VARCHAR}");
		}
		if (record.getUserName() != null) {
			sql.VALUES("user_name_", "#{userName,jdbcType=VARCHAR}");
		}
		if (record.getDictType() != null) {
			sql.VALUES("dict_type_", "#{dictType,jdbcType=VARCHAR}");
		}
		if (record.getDictName() != null) {
			sql.VALUES("dict_name_", "#{dictName,jdbcType=VARCHAR}");
		}
		if (record.getContent() != null) {
			sql.VALUES("content", "#{content,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.VALUES("create_date_", "#{createDate,jdbcType=TIMESTAMP}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_deliver_info
	 * @mbg.generated
	 */
	public String selectByExample(TbDeliverInfoModelExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("order_id_");
		sql.SELECT("user_id_");
		sql.SELECT("user_name_");
		sql.SELECT("dict_type_");
		sql.SELECT("dict_name_");
		sql.SELECT("content");
		sql.SELECT("create_date_");
		sql.FROM("tb_deliver_info");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_deliver_info
	 * @mbg.generated
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		TbDeliverInfoModel record = (TbDeliverInfoModel) parameter.get("record");
		TbDeliverInfoModelExample example = (TbDeliverInfoModelExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("tb_deliver_info");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=BIGINT}");
		}
		if (record.getOrderId() != null) {
			sql.SET("order_id_ = #{record.orderId,jdbcType=VARCHAR}");
		}
		if (record.getUserId() != null) {
			sql.SET("user_id_ = #{record.userId,jdbcType=VARCHAR}");
		}
		if (record.getUserName() != null) {
			sql.SET("user_name_ = #{record.userName,jdbcType=VARCHAR}");
		}
		if (record.getDictType() != null) {
			sql.SET("dict_type_ = #{record.dictType,jdbcType=VARCHAR}");
		}
		if (record.getDictName() != null) {
			sql.SET("dict_name_ = #{record.dictName,jdbcType=VARCHAR}");
		}
		if (record.getContent() != null) {
			sql.SET("content = #{record.content,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.SET("create_date_ = #{record.createDate,jdbcType=TIMESTAMP}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_deliver_info
	 * @mbg.generated
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("tb_deliver_info");
		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("order_id_ = #{record.orderId,jdbcType=VARCHAR}");
		sql.SET("user_id_ = #{record.userId,jdbcType=VARCHAR}");
		sql.SET("user_name_ = #{record.userName,jdbcType=VARCHAR}");
		sql.SET("dict_type_ = #{record.dictType,jdbcType=VARCHAR}");
		sql.SET("dict_name_ = #{record.dictName,jdbcType=VARCHAR}");
		sql.SET("content = #{record.content,jdbcType=VARCHAR}");
		sql.SET("create_date_ = #{record.createDate,jdbcType=TIMESTAMP}");
		TbDeliverInfoModelExample example = (TbDeliverInfoModelExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_deliver_info
	 * @mbg.generated
	 */
	public String updateByPrimaryKeySelective(TbDeliverInfoModel record) {
		SQL sql = new SQL();
		sql.UPDATE("tb_deliver_info");
		if (record.getOrderId() != null) {
			sql.SET("order_id_ = #{orderId,jdbcType=VARCHAR}");
		}
		if (record.getUserId() != null) {
			sql.SET("user_id_ = #{userId,jdbcType=VARCHAR}");
		}
		if (record.getUserName() != null) {
			sql.SET("user_name_ = #{userName,jdbcType=VARCHAR}");
		}
		if (record.getDictType() != null) {
			sql.SET("dict_type_ = #{dictType,jdbcType=VARCHAR}");
		}
		if (record.getDictName() != null) {
			sql.SET("dict_name_ = #{dictName,jdbcType=VARCHAR}");
		}
		if (record.getContent() != null) {
			sql.SET("content = #{content,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.SET("create_date_ = #{createDate,jdbcType=TIMESTAMP}");
		}
		sql.WHERE("id = #{id,jdbcType=BIGINT}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_deliver_info
	 * @mbg.generated
	 */
	protected void applyWhere(SQL sql, TbDeliverInfoModelExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}