package com.qigan.qiganshop.mapper;

import com.qigan.qiganshop.domain.TbLocalGoods;
import com.qigan.qiganshop.domain.TbLocalGoodsExample.Criteria;
import com.qigan.qiganshop.domain.TbLocalGoodsExample.Criterion;
import com.qigan.qiganshop.domain.TbLocalGoodsExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TbLocalGoodsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public String countByExample(TbLocalGoodsExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_local_goods");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public String deleteByExample(TbLocalGoodsExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_local_goods");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public String insertSelective(TbLocalGoods record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_local_goods");
        
        if (record.getCategoryId() != null) {
            sql.VALUES("category_id", "#{categoryId,jdbcType=BIGINT}");
        }
        
        if (record.getTbGoodsid() != null) {
            sql.VALUES("tb_goodsId", "#{tbGoodsid,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsSort() != null) {
            sql.VALUES("goods_sort", "#{goodsSort,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsEnable() != null) {
            sql.VALUES("goods_enable", "#{goodsEnable,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public String selectByExample(TbLocalGoodsExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("category_id");
        } else {
            sql.SELECT("category_id");
        }
        sql.SELECT("tb_goodsId");
        sql.SELECT("goods_sort");
        sql.SELECT("goods_enable");
        sql.FROM("tb_local_goods");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TbLocalGoods record = (TbLocalGoods) parameter.get("record");
        TbLocalGoodsExample example = (TbLocalGoodsExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("tb_local_goods");
        
        if (record.getCategoryId() != null) {
            sql.SET("category_id = #{record.categoryId,jdbcType=BIGINT}");
        }
        
        if (record.getTbGoodsid() != null) {
            sql.SET("tb_goodsId = #{record.tbGoodsid,jdbcType=VARCHAR}");
        }
        
        if (record.getGoodsSort() != null) {
            sql.SET("goods_sort = #{record.goodsSort,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsEnable() != null) {
            sql.SET("goods_enable = #{record.goodsEnable,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_local_goods");
        
        sql.SET("category_id = #{record.categoryId,jdbcType=BIGINT}");
        sql.SET("tb_goodsId = #{record.tbGoodsid,jdbcType=VARCHAR}");
        sql.SET("goods_sort = #{record.goodsSort,jdbcType=INTEGER}");
        sql.SET("goods_enable = #{record.goodsEnable,jdbcType=VARCHAR}");
        
        TbLocalGoodsExample example = (TbLocalGoodsExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TbLocalGoods record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_local_goods");
        
        if (record.getGoodsSort() != null) {
            sql.SET("goods_sort = #{goodsSort,jdbcType=INTEGER}");
        }
        
        if (record.getGoodsEnable() != null) {
            sql.SET("goods_enable = #{goodsEnable,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("category_id = #{categoryId,jdbcType=BIGINT}");
        sql.WHERE("tb_goodsId = #{tbGoodsid,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_local_goods
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TbLocalGoodsExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}