package com.qigan.qiganshop.mapper;

import com.qigan.qiganshop.domain.TbPushRecord;
import com.qigan.qiganshop.domain.TbPushRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TbPushRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbPushRecordSqlProvider.class, method="countByExample")
    long countByExample(TbPushRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TbPushRecordSqlProvider.class, method="deleteByExample")
    int deleteByExample(TbPushRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_push_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_push_record (id, push_title, ",
        "push_no, push_num, ",
        "push_type, create_date, ",
        "push_message)",
        "values (#{id,jdbcType=BIGINT}, #{pushTitle,jdbcType=VARCHAR}, ",
        "#{pushNo,jdbcType=VARCHAR}, #{pushNum,jdbcType=INTEGER}, ",
        "#{pushType,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{pushMessage,jdbcType=LONGVARCHAR})"
    })
    int insert(TbPushRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @InsertProvider(type=TbPushRecordSqlProvider.class, method="insertSelective")
    int insertSelective(TbPushRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbPushRecordSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="push_title", property="pushTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="push_no", property="pushNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="push_num", property="pushNum", jdbcType=JdbcType.INTEGER),
        @Result(column="push_type", property="pushType", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="push_message", property="pushMessage", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<TbPushRecord> selectByExampleWithBLOBs(TbPushRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbPushRecordSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="push_title", property="pushTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="push_no", property="pushNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="push_num", property="pushNum", jdbcType=JdbcType.INTEGER),
        @Result(column="push_type", property="pushType", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TbPushRecord> selectByExample(TbPushRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, push_title, push_no, push_num, push_type, create_date, push_message",
        "from tb_push_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="push_title", property="pushTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="push_no", property="pushNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="push_num", property="pushNum", jdbcType=JdbcType.INTEGER),
        @Result(column="push_type", property="pushType", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="push_message", property="pushMessage", jdbcType=JdbcType.LONGVARCHAR)
    })
    TbPushRecord selectByPrimaryKey(Long id);
    
    @SelectProvider(type=TbPushRecordSqlProvider.class, method="selectByCodition")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="push_title", property="pushTitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="push_no", property="pushNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="push_num", property="pushNum", jdbcType=JdbcType.INTEGER),
        @Result(column="push_type", property="pushType", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="push_message", property="pushMessage", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<TbPushRecord> selectByCodition(TbPushRecord model);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbPushRecordSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TbPushRecord record, @Param("example") TbPushRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbPushRecordSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") TbPushRecord record, @Param("example") TbPushRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbPushRecordSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TbPushRecord record, @Param("example") TbPushRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbPushRecordSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TbPushRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @Update({
        "update tb_push_record",
        "set push_title = #{pushTitle,jdbcType=VARCHAR},",
          "push_no = #{pushNo,jdbcType=VARCHAR},",
          "push_num = #{pushNum,jdbcType=INTEGER},",
          "push_type = #{pushType,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "push_message = #{pushMessage,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(TbPushRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_push_record
     *
     * @mbg.generated
     */
    @Update({
        "update tb_push_record",
        "set push_title = #{pushTitle,jdbcType=VARCHAR},",
          "push_no = #{pushNo,jdbcType=VARCHAR},",
          "push_num = #{pushNum,jdbcType=INTEGER},",
          "push_type = #{pushType,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TbPushRecord record);
}