package com.qigan.qiganshop.mapper;

import com.qigan.qiganshop.domain.TbDictModel;
import com.qigan.qiganshop.domain.TbDictModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TbDictModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbDictModelSqlProvider.class, method="countByExample")
    long countByExample(TbDictModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TbDictModelSqlProvider.class, method="deleteByExample")
    int deleteByExample(TbDictModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_dict",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_dict (id, dict_type_, ",
        "dict_code_, dict_name_, ",
        "create_date_, update_date_, ",
        "creater, updater)",
        "values (#{id,jdbcType=BIGINT}, #{dictType,jdbcType=VARCHAR}, ",
        "#{dictCode,jdbcType=VARCHAR}, #{dictName,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP}, ",
        "#{creater,jdbcType=VARCHAR}, #{updater,jdbcType=VARCHAR})"
    })
    int insert(TbDictModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @InsertProvider(type=TbDictModelSqlProvider.class, method="insertSelective")
    int insertSelective(TbDictModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @SelectProvider(type=TbDictModelSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dict_type_", property="dictType", jdbcType=JdbcType.VARCHAR),
        @Result(column="dict_code_", property="dictCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="dict_name_", property="dictName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date_", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_date_", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creater", property="creater", jdbcType=JdbcType.VARCHAR),
        @Result(column="updater", property="updater", jdbcType=JdbcType.VARCHAR)
    })
    List<TbDictModel> selectByExample(TbDictModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, dict_type_, dict_code_, dict_name_, create_date_, update_date_, creater, ",
        "updater",
        "from tb_dict",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="dict_type_", property="dictType", jdbcType=JdbcType.VARCHAR),
        @Result(column="dict_code_", property="dictCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="dict_name_", property="dictName", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date_", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_date_", property="updateDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creater", property="creater", jdbcType=JdbcType.VARCHAR),
        @Result(column="updater", property="updater", jdbcType=JdbcType.VARCHAR)
    })
    TbDictModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbDictModelSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TbDictModel record, @Param("example") TbDictModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbDictModelSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TbDictModel record, @Param("example") TbDictModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TbDictModelSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TbDictModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbg.generated
     */
    @Update({
        "update tb_dict",
        "set dict_type_ = #{dictType,jdbcType=VARCHAR},",
          "dict_code_ = #{dictCode,jdbcType=VARCHAR},",
          "dict_name_ = #{dictName,jdbcType=VARCHAR},",
          "create_date_ = #{createDate,jdbcType=TIMESTAMP},",
          "update_date_ = #{updateDate,jdbcType=TIMESTAMP},",
          "creater = #{creater,jdbcType=VARCHAR},",
          "updater = #{updater,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TbDictModel record);
}