package com.qigan.qiganshop.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbOrderCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public TbOrderCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(Long value) {
            addCriterion("comment_id =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(Long value) {
            addCriterion("comment_id <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(Long value) {
            addCriterion("comment_id >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("comment_id >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(Long value) {
            addCriterion("comment_id <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(Long value) {
            addCriterion("comment_id <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<Long> values) {
            addCriterion("comment_id in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<Long> values) {
            addCriterion("comment_id not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(Long value1, Long value2) {
            addCriterion("comment_id between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(Long value1, Long value2) {
            addCriterion("comment_id not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(String value) {
            addCriterion("orderId =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(String value) {
            addCriterion("orderId <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(String value) {
            addCriterion("orderId >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(String value) {
            addCriterion("orderId >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(String value) {
            addCriterion("orderId <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(String value) {
            addCriterion("orderId <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLike(String value) {
            addCriterion("orderId like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotLike(String value) {
            addCriterion("orderId not like", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<String> values) {
            addCriterion("orderId in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<String> values) {
            addCriterion("orderId not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(String value1, String value2) {
            addCriterion("orderId between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(String value1, String value2) {
            addCriterion("orderId not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelIsNull() {
            addCriterion("delivery_level is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelIsNotNull() {
            addCriterion("delivery_level is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelEqualTo(BigDecimal value) {
            addCriterion("delivery_level =", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelNotEqualTo(BigDecimal value) {
            addCriterion("delivery_level <>", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelGreaterThan(BigDecimal value) {
            addCriterion("delivery_level >", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("delivery_level >=", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelLessThan(BigDecimal value) {
            addCriterion("delivery_level <", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("delivery_level <=", value, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelIn(List<BigDecimal> values) {
            addCriterion("delivery_level in", values, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelNotIn(List<BigDecimal> values) {
            addCriterion("delivery_level not in", values, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("delivery_level between", value1, value2, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryLevelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("delivery_level not between", value1, value2, "deliveryLevel");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentIsNull() {
            addCriterion("delivery_comment is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentIsNotNull() {
            addCriterion("delivery_comment is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentEqualTo(String value) {
            addCriterion("delivery_comment =", value, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentNotEqualTo(String value) {
            addCriterion("delivery_comment <>", value, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentGreaterThan(String value) {
            addCriterion("delivery_comment >", value, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentGreaterThanOrEqualTo(String value) {
            addCriterion("delivery_comment >=", value, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentLessThan(String value) {
            addCriterion("delivery_comment <", value, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentLessThanOrEqualTo(String value) {
            addCriterion("delivery_comment <=", value, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentLike(String value) {
            addCriterion("delivery_comment like", value, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentNotLike(String value) {
            addCriterion("delivery_comment not like", value, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentIn(List<String> values) {
            addCriterion("delivery_comment in", values, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentNotIn(List<String> values) {
            addCriterion("delivery_comment not in", values, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentBetween(String value1, String value2) {
            addCriterion("delivery_comment between", value1, value2, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andDeliveryCommentNotBetween(String value1, String value2) {
            addCriterion("delivery_comment not between", value1, value2, "deliveryComment");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelIsNull() {
            addCriterion("goods_level is null");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelIsNotNull() {
            addCriterion("goods_level is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelEqualTo(BigDecimal value) {
            addCriterion("goods_level =", value, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelNotEqualTo(BigDecimal value) {
            addCriterion("goods_level <>", value, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelGreaterThan(BigDecimal value) {
            addCriterion("goods_level >", value, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_level >=", value, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelLessThan(BigDecimal value) {
            addCriterion("goods_level <", value, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelLessThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_level <=", value, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelIn(List<BigDecimal> values) {
            addCriterion("goods_level in", values, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelNotIn(List<BigDecimal> values) {
            addCriterion("goods_level not in", values, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_level between", value1, value2, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsLevelNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_level not between", value1, value2, "goodsLevel");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentIsNull() {
            addCriterion("goods_comment is null");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentIsNotNull() {
            addCriterion("goods_comment is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentEqualTo(String value) {
            addCriterion("goods_comment =", value, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentNotEqualTo(String value) {
            addCriterion("goods_comment <>", value, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentGreaterThan(String value) {
            addCriterion("goods_comment >", value, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentGreaterThanOrEqualTo(String value) {
            addCriterion("goods_comment >=", value, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentLessThan(String value) {
            addCriterion("goods_comment <", value, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentLessThanOrEqualTo(String value) {
            addCriterion("goods_comment <=", value, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentLike(String value) {
            addCriterion("goods_comment like", value, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentNotLike(String value) {
            addCriterion("goods_comment not like", value, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentIn(List<String> values) {
            addCriterion("goods_comment in", values, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentNotIn(List<String> values) {
            addCriterion("goods_comment not in", values, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentBetween(String value1, String value2) {
            addCriterion("goods_comment between", value1, value2, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andGoodsCommentNotBetween(String value1, String value2) {
            addCriterion("goods_comment not between", value1, value2, "goodsComment");
            return (Criteria) this;
        }

        public Criteria andCommentContextIsNull() {
            addCriterion("comment_context is null");
            return (Criteria) this;
        }

        public Criteria andCommentContextIsNotNull() {
            addCriterion("comment_context is not null");
            return (Criteria) this;
        }

        public Criteria andCommentContextEqualTo(String value) {
            addCriterion("comment_context =", value, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextNotEqualTo(String value) {
            addCriterion("comment_context <>", value, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextGreaterThan(String value) {
            addCriterion("comment_context >", value, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextGreaterThanOrEqualTo(String value) {
            addCriterion("comment_context >=", value, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextLessThan(String value) {
            addCriterion("comment_context <", value, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextLessThanOrEqualTo(String value) {
            addCriterion("comment_context <=", value, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextLike(String value) {
            addCriterion("comment_context like", value, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextNotLike(String value) {
            addCriterion("comment_context not like", value, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextIn(List<String> values) {
            addCriterion("comment_context in", values, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextNotIn(List<String> values) {
            addCriterion("comment_context not in", values, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextBetween(String value1, String value2) {
            addCriterion("comment_context between", value1, value2, "commentContext");
            return (Criteria) this;
        }

        public Criteria andCommentContextNotBetween(String value1, String value2) {
            addCriterion("comment_context not between", value1, value2, "commentContext");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNull() {
            addCriterion("user_phone is null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNotNull() {
            addCriterion("user_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneEqualTo(String value) {
            addCriterion("user_phone =", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotEqualTo(String value) {
            addCriterion("user_phone <>", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThan(String value) {
            addCriterion("user_phone >", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_phone >=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThan(String value) {
            addCriterion("user_phone <", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThanOrEqualTo(String value) {
            addCriterion("user_phone <=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLike(String value) {
            addCriterion("user_phone like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotLike(String value) {
            addCriterion("user_phone not like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIn(List<String> values) {
            addCriterion("user_phone in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotIn(List<String> values) {
            addCriterion("user_phone not in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneBetween(String value1, String value2) {
            addCriterion("user_phone between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotBetween(String value1, String value2) {
            addCriterion("user_phone not between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_comment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_order_comment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}