package com.qigan.qiganshop.domain;

public class TbLocalGoods extends TbLocalGoodsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_goods.goods_sort
     *
     * @mbg.generated
     */
    private Integer goodsSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_local_goods.goods_enable
     *
     * @mbg.generated
     */
    private String goodsEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_goods.goods_sort
     *
     * @return the value of tb_local_goods.goods_sort
     *
     * @mbg.generated
     */
    public Integer getGoodsSort() {
        return goodsSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_goods.goods_sort
     *
     * @param goodsSort the value for tb_local_goods.goods_sort
     *
     * @mbg.generated
     */
    public void setGoodsSort(Integer goodsSort) {
        this.goodsSort = goodsSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_local_goods.goods_enable
     *
     * @return the value of tb_local_goods.goods_enable
     *
     * @mbg.generated
     */
    public String getGoodsEnable() {
        return goodsEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_local_goods.goods_enable
     *
     * @param goodsEnable the value for tb_local_goods.goods_enable
     *
     * @mbg.generated
     */
    public void setGoodsEnable(String goodsEnable) {
        this.goodsEnable = goodsEnable == null ? null : goodsEnable.trim();
    }
}